[package]
name = "glide"
version = "0.1.0"
authors = ["Philippe Normand <phil@base-art.net>"]

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
gdk = { git = "https://github.com/gtk-rs/gdk" }
gio = { git = "https://github.com/gtk-rs/gio" }
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs" }
gstreamer-player = { git = "https://github.com/sdroege/gstreamer-rs" }
gstreamer-video = { git = "https://github.com/sdroege/gstreamer-rs" }
gtk = { git = "https://github.com/gtk-rs/gtk", features = ["v3_6"] }
send-cell = "0.1"
