[package]
name = "glide"
version = "0.3.0"
authors = ["Philippe Normand <phil@base-art.net>"]
keywords = ["multimedia", "gstreamer", "gtk", "playback"]
repository = "https://github.com/philn/glide"
readme = "README.md"
description = "Cross-platform media player based on GStreamer and GTK+"
license = "MIT"

[dependencies]
cairo-rs = "0.4.1"
glib = "0.5.0"
gdk = "0.8.0"
gio = "0.4.0"
gstreamer = "0.11.1"
gstreamer-player = "0.11"
gstreamer-video = "0.11"
gtk = { version = "0.4.0", features = ["v3_12"] }
send-cell = "0.1"
lazy_static = "1.0"
closet = "0.2.2"
self_update = "0.4"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
dirs = "0.3.1"
failure = "0.1"
failure_derive = "0.1"
sha2 = "0.7.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.5.1"
