[package]
name = "glide"
version = "0.5.6"
authors = ["Philippe Normand <phil@base-art.net>"]
keywords = ["multimedia", "gstreamer", "gtk", "playback"]
repository = "https://github.com/philn/glide"
readme = "README.md"
description = "Cross-platform media player based on GStreamer and GTK+"
license = "MIT"
edition = "2018"

[dependencies]
glib = "0.10"
gdk = "0.13"
gio = "0.9"
gstreamer = "0.16"
gstreamer-player = "0.16"
gstreamer-video = "0.16"
gtk = { version = "0.9", features = ["v3_16"] }
lazy_static = "1.4"
self_update = { version = "0.7", optional = true }
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
failure = "0.1"
sha2 = "0.8"
crossbeam-channel = "0.3"
directories = "2.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6"

[features]
self-updater = ["self_update"]
