[package]
name = "glide"
version = "0.4.0"
authors = ["Philippe Normand <phil@base-art.net>"]
keywords = ["multimedia", "gstreamer", "gtk", "playback"]
repository = "https://github.com/philn/glide"
readme = "README.md"
description = "Cross-platform media player based on GStreamer and GTK+"
license = "MIT"

[dependencies]
cairo-rs = { git = "https://github.com/gtk-rs/cairo.git"}
glib = { git = "https://github.com/gtk-rs/glib.git"}
gdk = { git = "https://github.com/gtk-rs/gdk.git"}
gio = { git = "https://github.com/gtk-rs/gio.git"}
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs.git" }
gstreamer-player = { git = "https://github.com/sdroege/gstreamer-rs.git" }
gstreamer-video = { git = "https://github.com/sdroege/gstreamer-rs.git" }
gtk = { git = "https://github.com/gtk-rs/gtk.git", features = ["v3_12"]}
lazy_static = "1.0"
gobject-sys = { git = "https://github.com/gtk-rs/sys.git"}
self_update = "0.4"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
dirs = "0.3.1"
failure = "0.1"
failure_derive = "0.1"
sha2 = "0.7.0"
crossbeam-channel = "0.2.4"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.5.1"
