[package]
name = "glide"
version = "0.5.6"
authors = ["Philippe Normand <phil@base-art.net>"]
keywords = ["multimedia", "gstreamer", "gtk", "playback"]
repository = "https://github.com/philn/glide"
readme = "README.md"
description = "Cross-platform media player based on GStreamer and GTK+"
license = "MIT"
edition = "2018"

[dependencies]
glib = "0.8.0"
gdk = "0.11.0"
gio = "0.7.0"
gstreamer = "0.14.0"
gstreamer-player = "0.14.0"
gstreamer-video = "0.14.0"
gtk = { version = "0.7.0", features = ["v3_16"] }
lazy_static = "1.3.0"
self_update = { version = "0.5.1", optional = true }
serde_json = "1.0.39"
serde_derive = "1.0.93"
serde = "1.0.93"
failure = "0.1.5"
sha2 = "0.8.0"
crossbeam-channel = "0.3.8"
directories = "2.0.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6.4"
objc = "0.2"
cocoa = "0.17.0"

[features]
self-updater = ["self_update"]
