[package]
name = "glide"
version = "0.2.0"
authors = ["Philippe Normand <phil@base-art.net>"]
keywords = ["multimedia", "gstreamer", "gtk", "playback"]
repository = "https://github.com/philn/glide"
readme = "README.rst"
description = "Cross-platform media player based on GStreamer and GTK+"
license = "MIT"

[dependencies]
cairo-rs = "0.3.0"
glib = "0.4.0"
gdk = "0.7.0"
gio = "0.3.0"
gstreamer = "0.10.1"
gstreamer-player = "0.10.1"
gstreamer-video = "0.10.1"
gtk = { version = "0.3.0", features = ["v3_12"] }
send-cell = "0.1"
lazy_static = "1.0"
closet = "0.2.2"
self_update = "0.4"