[package]
name = "glide"
version = "0.5.6"
authors = ["Philippe Normand <phil@base-art.net>"]
keywords = ["multimedia", "gstreamer", "gtk", "playback"]
repository = "https://github.com/philn/glide"
readme = "README.md"
description = "Cross-platform media player based on GStreamer and GTK+"
license = "MIT"
edition = "2018"

[dependencies]
glib = "0.9"
gio = "0.8"
gstreamer = "0.15"
gstreamer-player = "0.15"
gstreamer-video = "0.15"
lazy_static = "1.4.0"
self_update = { version = "0.7.0", optional = true }
serde_json = "1.0.41"
serde_derive = "1.0.101"
serde = "1.0.101"
failure = "0.1.5"
sha2 = "0.8.0"
crossbeam-channel = "0.3.9"
directories = "2.0.2"

[target.'cfg(target_os = "linux")'.dependencies]
gdk = "0.12"
gtk = { version = "0.8.0", features = ["v3_20"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.7"
objc = "0.2"
cocoa = "0.20"
fruitbasket = { git = "https://github.com/mrmekon/fruitbasket" }
gobject-sys = "0.9"

[features]
self-updater = ["self_update"]
